name: Build PeRGio Clicker EXE

on:
  push:
    tags:
      - 'v*'      # όταν κάνεις tag (π.χ. v1.0.0)
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --icon icon.ico --name "PeRGio_Clicker" PeRGio_Clicker.py
          copy coords_minutes.json dist\\coords_minutes.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PeRGio_Clicker_exe
          path: dist/PeRGio_Clicker.exe

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/PeRGio_Clicker.exe
